### ISSUE TITLE
Files and Images Are Not Imported

### ISSUE THREAD

**Issue by phptek** [phptek/silverstripe-exodus#14]
Run a crawl and then import. Both run A-OK for page-content, but despite what is selected for the parent node for images, nothing is ever imported. The `exodus.log` doesn't contain anything interesting either.

**Comment by phptek** [comment]
This appears to be dwn to the naive way in which the module was written orignally for Silverstripe 3 and skirted around Silverstripe's upload logic. In SS4 we're now using hashes for directory names, so we need to involve the file-uploaded logic directly.

**Comment by phptek** [comment]
See the work which gets us some of the way there. Code comments indicate what the underlying issue is, but I've run out of (consistent) time to work on it: Branch: `issue/file-write-fixes`

**Comment by michalkleiner** [comment]
Open a draft PR perhaps for easier review?

**Comment by phptek** [comment]
> Open a draft PR perhaps for easier review?

See #22

**Comment by phptek** [comment]
Note to self:

```
                    $folder = Folder::find_or_make($filePath);
                    $image = Image::create();

                    //create a new Image file and a parent folder
                    $image->setFromLocalFile($filePath);
                    $image->ParentID = $folder->ID;
                    $image->write();
                    $image->publishSingle();
```
